services:
  ros2_jazzy:
    build:
      context: ..                      # ← parent dir (~/jazzy_ws)
      dockerfile: docker/Dockerfile    # ← Dockerfile relative to context
    container_name: ros2_jazzy_3irobotics
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev:rw
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    group_add:
      - dialout
    privileged: true
    stdin_open: true
    tty: true
